const tracker_type = {
  PLAYER_LOOKING_FOR_TEAM: 'PLAYER_LOOKING_FOR_TEAM',
  PLAYER_LOOKING_FOR_GAME: 'PLAYER_LOOKING_FOR_GAME',
  TEAM_LOOKING_FOR_PLAYER: 'TEAM_LOOKING_FOR_PLAYER',
  TEAM_LOOKING_FOR_PLAYERS: 'TEAM_LOOKING_FOR_PLAYERS'
};

const game_type = { OFFICIAL: 'OFFICIAL', CASUAL: 'CASUAL', UNKNOWN: 'UNKNOWN' };

const request_status = {
  DRAFT: 'DRAFT', PUBLISHED: 'PUBLISHED', HAS_RESPONSES: 'HAS_RESPONSES', PARTIALLY_FILLED: 'PARTIALLY_FILLED', FILLED: 'FILLED', CLOSED: 'CLOSED', CANCELLED: 'CANCELLED', EXPIRED: 'EXPIRED', ARCHIVED: 'ARCHIVED'
};

const response_status = { REQUESTED: 'REQUESTED', ACCEPTED: 'ACCEPTED', DECLINED: 'DECLINED', CANCELLED_BY_USER: 'CANCELLED_BY_USER', CANCELLED_BY_AUTHOR: 'CANCELLED_BY_AUTHOR', EXPIRED: 'EXPIRED' };
const location_mode = { ALL: 'ALL', ZONE: 'ZONE', DISTRICTS: 'DISTRICTS' };
const zone = { NORTH: 'NORTH', SOUTH: 'SOUTH', CENTER: 'CENTER' };
const district = {
  ALL: 'ALL', ADMIRALTEYSKY: 'ADMIRALTEYSKY', VASILEOSTROVSKY: 'VASILEOSTROVSKY', VYBORGSKY: 'VYBORGSKY', KALININSKY: 'KALININSKY', KIROVSKY: 'KIROVSKY', KOLPINSKY: 'KOLPINSKY', KRASNOGVARDEYSKY: 'KRASNOGVARDEYSKY', KRASNOSELSKY: 'KRASNOSELSKY', KRONSHTADTSKY: 'KRONSHTADTSKY', KURORTNY: 'KURORTNY', MOSKOVSKY: 'MOSKOVSKY', NEVSKY: 'NEVSKY', PETROGRADSKY: 'PETROGRADSKY', PETRODVORTSOVY: 'PETRODVORTSOVY', PRIMORSKY: 'PRIMORSKY', PUSHKINSKY: 'PUSHKINSKY', FRUNZENSKY: 'FRUNZENSKY', TSENTRALNY: 'TSENTRALNY'
};
const level = { BEGINNER: 'BEGINNER', AMATEUR: 'AMATEUR', MIDDLE: 'MIDDLE', ABOVE_MIDDLE: 'ABOVE_MIDDLE', HIGH: 'HIGH', ANY: 'ANY' };
const format = { FIVE_A_SIDE: 'FIVE_A_SIDE', SIX_A_SIDE: 'SIX_A_SIDE', SEVEN_A_SIDE: 'SEVEN_A_SIDE', EIGHT_A_SIDE: 'EIGHT_A_SIDE', ELEVEN_A_SIDE: 'ELEVEN_A_SIDE', OTHER: 'OTHER', ANY: 'ANY' };
const position = { GOALKEEPER: 'GOALKEEPER', DEFENDER: 'DEFENDER', MIDFIELDER: 'MIDFIELDER', FORWARD: 'FORWARD', FIELD_PLAYER: 'FIELD_PLAYER', UNIVERSAL: 'UNIVERSAL', ANY: 'ANY', MIXED: 'MIXED' };
const payment_type = { FREE: 'FREE', FIXED_PRICE: 'FIXED_PRICE', FIELD_SHARE: 'FIELD_SHARE', UNKNOWN: 'UNKNOWN' };
const request_source = { BOT: 'BOT', SHARED_LINK: 'SHARED_LINK', ADMIN_IMPORT: 'ADMIN_IMPORT' };

const zoneToDistricts = {
  NORTH: ['VYBORGSKY', 'KALININSKY', 'KRASNOGVARDEYSKY', 'KURORTNY', 'PRIMORSKY'],
  SOUTH: ['KIROVSKY', 'KRASNOSELSKY', 'KOLPINSKY', 'MOSKOVSKY', 'NEVSKY', 'PUSHKINSKY', 'FRUNZENSKY'],
  CENTER: ['ADMIRALTEYSKY', 'VASILEOSTROVSKY', 'PETROGRADSKY', 'TSENTRALNY']
};

module.exports = { tracker_type, game_type, request_status, response_status, location_mode, zone, district, level, format, position, payment_type, request_source, zoneToDistricts };
